version: '3.9'

services:
  #Web HTML Agencia
  web_agencia:
    build: ./App_Agencia
    ports:
      - "8083:80"
  #Web HTML Agencia
  landing:
    build: ./App_Landing
    ports:
      - "8084:80"

  db_wordpress:
    build: ./cms/database
    container_name: db_wordpress
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: wordpress
      MYSQL_USER: manager
      MYSQL_PASSWORD: secret
    networks:
      - wpsite

  phpmyadmin:
    depends_on:
      - db_wordpress
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db_wordpress
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - wpsite

  wordpress:
    build: cms/vshowcase
    container_name: wordpress
    depends_on:
      - db_wordpress
    ports:
      - '8000:80'
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db_wordpress:3306
      WORDPRESS_DB_USER: manager
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wpsite

  db_flask:
    build: flask/db_data
    container_name: db_flask
    restart: unless-stopped
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: municipios
    networks:
      - wpsite

  flask_project:
    build: flask/app
    container_name: flask_project
    depends_on:
      - db_flask
    ports:
      - '5000:5000'
    restart: unless-stopped
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DATABASE_HOST: db_flask
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: password


      DATABASE_NAME: municipios
    networks:
      - wpsite

networks:
  wpsite:

volumes:
  db_data_wordpress:
  db_data_flask:
